### ISSUE TITLE
Add video data models

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#10]
See [here](https://github.com/signdict/website/wiki/Datamodel)

**Comment by bitboxer** [comment]
Okay, lets discuss the video data model here.

I currently have 1.000 videos on my disk from [de.wikisign.org](http://dgs.wikisign.org/Wiksign:Hauptseite). Sadly that page is defunct now, but we still need to link to it for
the videos to comply to the copyright and license.

A rough idea would be:

* it belongs to a user
* has states `uploaded, transcoded, waiting_for_review, published, deleted`
* has some way to hold  the `copyright` as text that we can show under the video "(Video by de.wikisign.org author Name)".
* the license that video is under, the videos from wikisign are under `by-sa-3.0-de`. Ours will also have a CC license attached to it. Not 100% sure wich version yet. But I am not sure if this should be a link to a license model with more info about the license (link, name, etc.).
* Link to original url. As I said, some videos are not from our site.

And then there are two fields in the description we don't need right now, but could start thinking on how to implement them (in a new ticket):

*  `has_many :votes` - stackoverflow like up/downvote system to find the most used sign for a language
* type (at first only word, but later also: phrases, lesson, ...) - to make it possible to add different kind of videos.

**Comment by EinLama** [comment]
Started working on a possible implementation. To be honest I have no idea if this is the phoenix way 😅 

See a7207aee08d4d9de67402fbe9ce41f0b31a86278

**Comment by bitboxer** [comment]
Awesome! And don't worry. I have no clue either. I am looking at a few apps and try to mimic their style 👍 . You can find some [here](https://elixirforum.com/t/recommended-example-phoenix-apps/2946/7)

**Comment by bitboxer** [comment]
The video is now on master. Thanks @EinLama ! Next step: business logic 🍰

**Comment by EinLama** [comment]
Working on the logic in #40

**Comment by bitboxer** [comment]
This is done now. Thanks @EinLama 
 ![Dinosaurs forming a conga line and dancing](http://i.giphy.com/3rgXBvnbXtxwaWmhr2.gif)
