### ISSUE TITLE
Import wikisign data

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#11]
I have a complete copy of the wikisign wiki on my disk, those need to be added to the site

**Comment by bitboxer** [comment]
The copy consists of a `.flv` and a `.json` with the same name. Here is an example of such an json file:

```
{
  "word": "Zufall",
  "word_link": "http://dgs.wikisign.org/Zufall",
  "author": "Philipps",
  "author_link": "http://dgs.wikisign.org/Benutzer:Philipps",
  "tags": [],
  "filename": "Zufall.flv"
}
```

Here is a zip containing the file to play around with:
[zufall.zip](https://github.com/signdict/website/files/819747/zufall.zip)

**Comment by bitboxer** [comment]
The videos are under the [by-sa-3.0-de]/https://creativecommons.org/licenses/by-sa/3.0/de/) as seen in the footer of [the page](http://dgs.wikisign.org/Wiksign:Hauptseite)

**Comment by bitboxer** [comment]
Ah and [here](http://blog.plataformatec.com.br/2016/04/running-migration-in-an-exrm-release/) is a nice hint on how to write such an importer that is accessible on production.

**Comment by bitboxer** [comment]
Ah and [here](http://blog.plataformatec.com.br/2016/04/running-migration-in-an-exrm-release/) is a nice hint on how to write such an importer that is accessible on production.

**Comment by bitboxer** [comment]
I now have added another source : http://gebaerdenlernen.de/ . Already downloaded the files to my computer, they are under a by-nc-sa/3.0/de license

**Comment by bitboxer** [comment]
This is done now.

**Comment by gulp21** [comment]
> I now have added another source : http://gebaerdenlernen.de/ . Already downloaded the files to my computer, they are under a by-nc-sa/3.0/de license

Is there a reason why the videos from "DGS für Mediziner" (e.g. infektion) and the example sentences have not been imported?

**Comment by bitboxer** [comment]
I only did one big import a couple of years ago. Could be that those have been added after that. I should dig out that old script and try to modify it to add those missing files.
