### ISSUE TITLE
Add search suggestions when typing

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#144]
The search box should show possible matches when starting to enter a word. Maybe this needs #168 to be finished before.

**Comment by jann** [comment]
@bitboxer I started  with the implementation of autocompletion in the search form. I pushed what I have to a work in progress branch here: https://github.com/signdict/website/compare/master...wip-autocomplete 
If you type in 'bear' in the search field you will see some basic autocompletion. So far so good...

Next step I did was adding the vue appolo library as described here: https://github.com/Akryum/vue-apollo. So then we have somthing like this: https://github.com/signdict/website/compare/master...wip2-autocomplete 

When reloading, I get a browser error like, reference error in zenObservable, which I dont understand...

Maybe a fresh pair of eyes could help :)

**Comment by bitboxer** [comment]
Oay, the problem is `ReferenceError: require is not defined[Weitere Informationen]`. require is a non standard javascript thing. You need `require.js` for this to work. The current setup does not use that. And I really don't want to add it to the javascript pipeline 😭 . 

There is an [issue](https://github.com/apollographql/apollo-link/issues/558) for this already.

**Comment by bitboxer** [comment]
@jann I did a major restructuring of the code because of the latest phoenix changes. Hope you don't have too many problems rebasing your code to it.

**Comment by bitboxer** [comment]
Ah and the issue that described your issue was closed on the 12th of april, so hopefully it is fixed for you, too 🤞

**Comment by bitboxer** [comment]
@jann I am now taking over this old ticket because I have someone paying me to implement some new features on signdict. Search suggestions is one of the features they need.

**Comment by jann** [comment]
Sure, no problem.
