### ISSUE TITLE
Directly open search hit if there's only one

### ISSUE THREAD

**Issue by EinLama** [signdict/website#154]
After searching, when there is only one hit, the result page could be skipped. Instead, I would like to see the suggested video directly.

Since there's little choices to make, why require another click?

When **no video** is found:
* show no results

When **exactly one video** is found:
* redirect to the video page

When **more than one video** is found:
* show the search result page

**Comment by bitboxer** [comment]
The only problem: currently the search is really fuzzy and people can get confused why they are redirected to a page with a word they didn't search for. We should only redirect if it is a 100% match or something really close.

**Comment by EinLama** [comment]
Oh, I see. I agree that this would lead to confusion.
