### ISSUE TITLE
What license do we want to use?

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#17]
We need to think about the license before we start working on this.

Possible candidates for me:

* MIT - really straight forward, giving everything away [TL&DR](https://tldrlegal.com/license/mit-license)
* MPL - Mozillas License. A nicer version of the GPL without the viral aspect of it. [TL&DR](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))

What do you think @EinLama ?

**Comment by bitboxer** [comment]
If anyone has other suggestions, feel free to post them, too.

**Comment by EinLama** [comment]
I like the MPL! But if you don't want to give licensing much thought, the MIT license is the easiest to adopt. No headaches, no worries. No control, though.

My vote for the MPL 😄

**Comment by EinLama** [comment]
Another suggestion would be [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29)

It gives a little more control than the MIT license, while being less restricting than the MPL.

**Comment by moonglum** [comment]
Did you consider copyleft licenses like the GPLv3? What are the reasons against it?

**Comment by bitboxer** [comment]
The MPL is a copyleft license. I prefer it to the GPL because it has no viral part in it. You can easily mix code under MPL with other things without having linking issues like the GPL has.

**Comment by moonglum** [comment]
But that's only relevant if you write a library/framework/... isn't it?

**Comment by bitboxer** [comment]
Not if you want to extract the video recording part of this app to something else. And I already have things in my mind that could use that part later on.

**Comment by bitboxer** [comment]
And there are other areas of the app that also could be extracted later on. The video integration on #12 for example. We would need to relicense it or keep it under GPL when we extract it.

**Comment by moonglum** [comment]
Then I would go with the Apache License.

**Comment by bitboxer** [comment]
Any reason why you prefer it to the MPL?

**Comment by bitboxer** [comment]
Asking because Apache is not Copyleft and is not compatible with GPL

**Comment by moonglum** [comment]
Apache is compatible with the GPL: https://www.gnu.org/licenses/license-list.html#apache2

**Comment by bitboxer** [comment]
Ah, perfect. Just read more about it. GPL >= 3 is compatible with Apache >= 2. Everything before is incompatible. What about the copyleft aspect? Do you think it is not relevant?

**Comment by moonglum** [comment]
MPL is only interesting for people that distribute the code. Let's say someone does a `dictnsign.org` website – as long as they don't distribute the code, they can do whatever the want 😃 They do not need to give you access to the code etc.

So what does it help?

**Comment by bitboxer** [comment]
Have to think about that. Currently I am leaning towards MPL because of the Copyleft part. If I extract some parts of the app into components, it would be good if the license for that would be copyleft...not sure yet.

**Comment by moonglum** [comment]
I think MPL is a solid choice, don't get me wrong 👍
