### ISSUE TITLE
configure to use ssl only

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#18]

**Comment by EinLama** [comment]
Which certificate do you plan to use? [Letsencrypt](https://letsencrypt.org/) would be a nice option.

**Comment by bitboxer** [comment]
The blog already uses Let's encrypt :wink: . I love that service.

**Comment by EinLama** [comment]
True! Didn't even notice the blog had SSL. Nice!

**Comment by bitboxer** [comment]
I activated it this morning 👍

**Comment by bitboxer** [comment]
This is now done. Including http2.
