### ISSUE TITLE
Add support for firefox webcam recording

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#223]
The bug that prevented us to add Firefox is [closed](https://bugzilla.mozilla.org/show_bug.cgi?id=1272371) and Firefox 55 is able to record again. Sadly the UI is a bit broken when activating it in Firefox. We need to investigate why and fix this.

**Comment by laurens** [comment]
I looked into this a bit. The [hack for retrieving the recorded video’s duration](https://github.com/signdict/website/blob/1b1c6e0b0151d2475ac2a0c9965abd07fd2b27eb/web/static/js/components/cutter.vue#L174) is not working in Firefox. The duration continues to be `Infinity` and with that all subsequent code for cutting the video is breaking. Did not find an alternative so far.

Tested in FF 55, OS X.

**Comment by bitboxer** [comment]
Oh noes. I suspected this but haven't tried yet. Another work around would be to measure the time of the recording directly and remember that. But this only helps if jumping to positions works with the firefox blobs.
