### ISSUE TITLE
Add page url to graphql

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#230]
I think it would be great to add the page url to the video and entry schemas of the graphql api. That way you could query using graphql and send the user to the correct page.

**Comment by bitboxer** [comment]
Maybe @jann has an idea how to do this? Any hints welcome.

**Comment by bitboxer** [comment]
And while we are at it, we could also change the originalHref and copyright to always return something. If the source is SignDict, it should have an originalHref with the page link and the copyright should have the name of the user in it.

**Comment by jann** [comment]
#235 adds the url attribute to our entry model. 
I have a few question regarding the rest.
- For each video we already have the url stored in the database (video_url attribute)? or is this attribute meant for something else?
- regarding originalHref and copyright: is the source is SignDict when the video was not previously imported, but recorded directly from the website?

**Comment by bitboxer** [comment]
Oh, nice. Thanks!

The video_url is the raw mp4 file. I would love to have the possibility to link to the webpage that plays the video. For example this link: https://signdict.org/entry/835-zug/video/950

The copyright: if the original source is SignDict, the originalHref is empty, we should add our page as source for those videos. That way people who want to use our videos always can use the orignalHref without checking if it is empty or not.

**Comment by bitboxer** [comment]
Closing this, the other missing things will be done in #771
