### ISSUE TITLE
Voting system for videos?

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#24]
there is no 1 right way to sign a word. There are lots of variants. And because of that I want to make it possible to upload several videos per word. But this makes it hard for learners to know what is the best word to learn.

We could add a voting system to find the most popular version for a word and crowdsource that part, too.

**Comment by jann** [comment]
i think this feature would be very usefull!

some questiobs:
- should only loggedin users be able to vote?
- should there be a max limit of votes per day?
- should a user be able to vote on one video more then once?
- should a user be able to up and downvote on the same video (to correct his/her vote) ?

**Comment by EinLama** [comment]
My thoughts:

* Only logged in users should be able to vote (to prevent misusage)
* Only one vote per video. But you can edit/correct your vote later (revote).

This should remove the need of introducing a max limit for votes.

**Comment by jann** [comment]
good ideas! 

just few more questions:

- when deleting a video, all its votes should be deleted, too?
- when deleting a user, the all votes on videos should be still there?

**Comment by EinLama** [comment]
When a video is deleted, all associated votes should be deleted, too.

Same for a user. If a user is deleted, delete his votes.

I think that a vote should only count as long as both references (the one to the video and the one to the user) exist.

**Comment by jann** [comment]
Cool thanks for the feedback. I would like to work on this feature. Will start probably end of this week.

**Comment by EinLama** [comment]
I spoke to @bitboxer in the meantime. We now have a status field for the video. This has implications on the deletion. Instead of removing a row form the database when a video is deleted, its `status` is set to `deleted`.

Regarding votes: it only has to be deleted once the video row is removed from the database, I think.

As for users: when a user is deleted, her videos status should be set to `deleted`, but we should not discard all videos directly. If we directly delete all rows on user deletion, we might lose many videos when a user with many uploads chooses to quit.

**Comment by EinLama** [comment]
@jann it would be great if you grabbed this ticket 👍 🎉

**Comment by bitboxer** [comment]
@jann in pr #56 you said that there is still stuff to do on this ticket. Can you document what is missing here so that everyone knows what is still to do before this can be closed? Thank you 👌

**Comment by jann** [comment]
Sure :)

- [ ] Make vote create and delete controller endpoints to respond to json. 
- [ ] Write js function that modifies vote create form to send ajax if js is supported. 
- [ ] Write js function that modifies vote delete link to send ajax if js is supported. 
- [ ] Add I18n to feedback messages when creating/deleting a vote.

**Comment by bitboxer** [comment]
I will take over and finish the tasks. I think the javascript/json stuff is not needed for now, the page works fine without js. Will add that later if someone finds this is really needed.

**Comment by bitboxer** [comment]
Added the translations in #80 and will ignore the s parts for now.
