### ISSUE TITLE
Adding bugsnag

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#28]
We should add [bugsnag](http://bugsnag.com) using [this](https://github.com/liefery/bugsnex).

If anyone has an opinion about another bug tracking service that is better, feel free to comment here 👍

**Comment by bitboxer** [comment]
Another option is rollbar with [this](https://github.com/elixir-addicts/rollbax)

**Comment by moonglum** [comment]
I'm using both Rollbar and Bugsnag. Bugsnag is better.

**Comment by bitboxer** [comment]
Okay, bugsnag it is 👍

**Comment by bitboxer** [comment]
I created a bugsnag account and tried to use the package, but got stuck, it didn't report any error. Will ask someone to help me with this 👍
