### ISSUE TITLE
add show entry page

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#36]
We need a page that shows a word and the attached videos

**Comment by jann** [comment]
this would be nice to have for my (vote feature)[https://github.com/signdict/website/issues/24], so I can put upvote links in it and try it out :) 
If no one is grabbing it, I will create a basic word controller with an show action in it and the appropriate template/view.

**Comment by bitboxer** [comment]
This needs #35, the data model behind it. But feel free to grab it if nobody started it when you start working on your vote feature.

**Comment by bitboxer** [comment]
To clearify: "word" is actually called "entry" in the datamodel. I renamed all tickets now.
