### ISSUE TITLE
search for an entry

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#37]
We need a page where we can select the language and search for a word in that language.

Simple postgres text indexing is enough for now. I have details on how to implement such a thing from previous jobs and can help with this.

**Comment by jann** [comment]
One question on this one. 
I think the tsvector needs the language of the word it is storing and loading it into the db. Are we currently only focusing on german or should that also be dynamic (e.g. some through some select menu with language when searching)?

**Comment by bitboxer** [comment]
Yes, it needs that language. And exactly for that I added the language model. A word belongs to a language. And the language has a default locale. We can use that locale to give postgres the correct hint for the index, right?

**Comment by jann** [comment]
I started this yesterday, but did not finish it. I doubt I will have time until mid of next week. So I put my stuff in this [branch](https://github.com/signdict/website/compare/37_search_for_entry?expand=1). Feel free to continue working on it or give feedback.

**Comment by bitboxer** [comment]
It would be awesome if this would be reachable under `/search?q=searchstring`. The landing page already tries to call that url if you press search 😉

**Comment by bitboxer** [comment]
I will take over now.

**Comment by bitboxer** [comment]
Ah and I will use this: http://rachbelaid.com/postgres-full-text-search-is-good-enough/ as guideline

**Comment by bitboxer** [comment]
Added a basic version with ilike now so that the beta site has a working search for now. Will add the text vector stuff now

**Comment by bitboxer** [comment]
https://github.com/signdict/website/pull/86

**Comment by bitboxer** [comment]
This is now done with tsvector and dynamic languages. Details can be seen in #87 .
