### ISSUE TITLE
Investigate what integration testing framework to use

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#5]
Read [this](https://semaphoreci.com/community/tutorials/integration-testing-phoenix-with-wallaby?utm_campaign=elixir_radar_83&utm_medium=email&utm_source=RD+Station) and figure out what is the best way to implement integration testing and add it to the project

**Comment by bitboxer** [comment]
So basically there is Hound and Wallaby. @EinLama do you have an opinion on this? If not I will try to read through a few things and decide 😉

**Comment by bitboxer** [comment]
Ah and [this](https://semaphoreci.com/community/tutorials/end-to-end-testing-in-elixir-with-hound) is a article about hound. The link in the issue description only deals with wallaby

**Comment by EinLama** [comment]
I fancy Wallaby a bit more. Both seem to be very similar. Wallaby is a bit more implicit than Hound. [Here's a comparison thread](https://elixirforum.com/t/wallaby-vs-hound/443/4).

I think we should go for one and look how it feels, maybe switch after a while if we run into problems.

Then again, I am not a huge fan of integration tests. View tests in combination with controller tests will ensure our frontend works. Will integration tests be an addition or a replacement for either view or controller tests? What are your opinions on this?

**Comment by bitboxer** [comment]
If you fancy Wallaby more, let's use it 👍 . Most of the times Controller and View Tests are enough.

I fancy integration tests for:

* Flows that have more than one page, e.g. User registration with more than one page (email validation etc) and move through several steps to complete
* Pages with javascript on it. As soon as I have a page with JS, I love to test that everything works as expected using integration tests. JS test are very brittle in my opinion and this makes sure we don't miss an important step. Having said that: JS needs it's own tests for all components. We can't test every code path in JS using integration tests. This would be way to slow :wink:

**Comment by EinLama** [comment]
I see, this makes perfect sense! :+1:

**Comment by bitboxer** [comment]
Done in #31
