### ISSUE TITLE
Add webpack and babel

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#53]
To prepare the js work we need to add webpack. That makes it also
easier to add lots of other css related things because lots of people are
using webpack nowadays.

See [here](http://matthewlehner.net/using-webpack-with-phoenix-and-elixir/) for details how to do it.

**Comment by moonglum** [comment]
I would strongly recommend to:

* Not use Webpack for CSS. Only use it for JS.
* Check out Rollup instead of Webpack. Webpack has a _huge_ problem: The output is not debuggable. That caused a lot of frustration for us in the current project.

**Comment by bitboxer** [comment]
What do you mean by not debuggable? You can add sourcemaps to the webpack output and then it should show up in the debugger correctly. And what do you suggest instead of webpack for the css/asset pipeline?

**Comment by bitboxer** [comment]
Disclaimer: I am getting really frustrated by the amount of people saying to me that i should *not* use a certain tool. I need to see examples how to use the tool you suggest and what exactly the advantages are 😿

**Comment by moonglum** [comment]
Nope, that's not the case @bitboxer. No matter if you do Sourcemaps or not, most of the time the stacktraces of an JS error are useless when using webpack, only showing you lines of generated code for module resolution that you never wrote. The real error gets lost in that confusion.

Trust me, I feel your frustration of all the people talking about which frontend tools are good or bad. But those webpack debugging problems have cost us multiple days. I don't know if you want to spend that amount of time in deep frustration.

**Comment by moonglum** [comment]
[Here](https://github.com/FND/javascript-boilerplate/tree/rollup) you can find the boilerplate for using Rollup. Rollup has the big advantage of creating readable output that is very, very close to what you wrote yourself.

**Comment by bitboxer** [comment]
Thanks for the longer explanation. So to clarify : your first bullet point should read as "use webpack only for the css and not js"?

**Comment by bitboxer** [comment]
Or do you have another tool instead for the asset pipeline?

**Comment by bitboxer** [comment]
Currently wondering if brunch for assets and rollup via [this](https://github.com/istr/rollup-brunch) is what you would prefer 🤔

**Comment by moonglum** [comment]
> Thanks for the longer explanation. So to clarify : your first bullet point should read as "use webpack only for the css and not js"?

Yes. *If* you use webpack, only use it for JS. Do not use it for CSS. For CSS simply use SCSS, PostCSS... whatever you prefer 😉 

> Or do you have another tool instead for the asset pipeline?

In my asset pipeline I currently use Webpack+Babel for JS (not recommended, as stated above. We will switch to something else soon) and SCSS for PostCSS 😉 

> Currently wondering if brunch for assets and rollup via this is what you would prefer 🤔

Definitely.

**Comment by bitboxer** [comment]
Okay, then I will try this setup:

* keep brunch
* add postcss
* use rollup for js

Lets see what happens. If it breaks it should not be too hard to switch to something else I think.

**Comment by bitboxer** [comment]
Okay, added postcss in #61 . Will add rollup when I think that I need it. Till then I will close this issue.
