### ISSUE TITLE
Find a way to create an easy backend

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#6]
We need to have a nice backend to edit data. What should we use? Are there tools that help us that are similar to [Administrate](https://github.com/thoughtbot/administrate) ?

**Comment by EinLama** [comment]
The automatic views generated by `mix phoenix.gen.html` should suffice, I think. It generates views (which look pretty close to what Adminstrate offers) along with the model, test-stubs and migration.

After that, we only need to change the routes to restrict access to admin users (insert the correct Plug, for example) and we're set.

See the [hexdocs](https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Html.html) for more information about gen.html.

**Comment by EinLama** [comment]
Since the views for all models will be similar, it's easy to change their style with CSS - or add a menu with all models to the sidebar in the application layout.

**Comment by bitboxer** [comment]
Yes, that is true. We only need to write custom filters and search for the index pages. Let's close this for now
