### ISSUE TITLE
add about page

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#70]
on the about page we need to explain the concept of the page, how it started and encourage everyone to participate

**Comment by bitboxer** [comment]
So, dir schon mal das Ticket zugewiesen 👍

**Comment by bitboxer** [comment]
Mir ist jetzt eingefallen, was wir als Text nehmen sollten: 

http://blog.signdict.org/about/

Da gibt es englische und deutsche texte 👍 .

Mach aber erstmal das ganze in englisch ohne gettext und dann überlege ich mir mal, was wir da nehmen können um das einfach zu übersetzen ohne jeden absatz einzeln in gettext zu packen.

**Comment by Rantastique** [comment]
Bin zwar am Wochenende nicht, wie geplant, dazu gekommen, aber bis Mittwoch schaffe ich das :)
